### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lingling-fan** [TKJElectronics/BalanduinoAndroidApp#6]
//package name: com.tkjelectronics.balanduino
//version: 0.6.3 / 0.6.3-usb
//target sdk version: android-18
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tkjelectronics.balanduino/com.tkjelectronics.balanduino.BalanduinoActivity}: java.lang.NullPointerException
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NullPointerException
 	at com.tkjelectronics.balanduino.BalanduinoActivity.onStart(BalanduinoActivity.java:288)
 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
 	at android.app.Activity.performStart(Activity.java:5143)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)

**Comment by Lauszus** [comment]
What device are you running the app on?
